matrix:
  include:
    - os: osx
      osx_image: xcode12

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda -y
  - source $HOME/miniconda/bin/activate
  - conda init zsh
  - pip install pytest
  - pip install -e .

script:
  - pytest

deploy:
  provider: pypi
  user: maxhumber
  password: $PYPI_PASSWORD
  on:
    tags: true
