matrix:
  include:
    - os: osx
      osx_image: xcode12
      python: "3.7"

deploy:
  provider: pypi
  user: maxhumber
  password: $PYPI_PASSWORD
  on:
    tags: true

install:
  - "pip install -e ."
  - "pip install pytest"

script:
  - pytest
